import type { WalletCatalogEntry } from './types'

export const BLOCKED_REGISTRY_SLUGS = ['okx-wallet-1', 'ready', 'yowallet', 'safewallet']

export const WALLET_CATALOG: WalletCatalogEntry[] = [
    {
        id: 'metamask',
        displayName: 'MetaMask',
        rdns: ['io.metamask', 'io.metamask.mobile'],
        nativeIds: {
            evm: ['metaMaskSDK'],
            svm: ['MetaMask'],
            tron: ['MetaMask'],
            bitcoin: ['io.metamask.bitcoin'],
        },
        nameAliases: ['metamasksdk'],
        featuredRank: 1,
        iconKey: 'metamask',
        deepLink: uri => `https://metamask.app.link/wc?uri=${encodeURIComponent(uri)}`,
    },
    {
        id: 'ready',
        displayName: 'Ready (formerly Argent)',
        nativeIds: { evm: ['ready (formerly argent)'] },
        nameAliases: ['argent', 'ready'],
        featuredRank: 2,
        iconKey: 'argent',
    },
    {
        id: 'rainbow',
        displayName: 'Rainbow',
        rdns: ['me.rainbow'],
        nameAliases: ['app.rainbow'],
        featuredRank: 3,
        iconKey: 'rainbow',
        deepLink: (uri, { isIOS }) => isIOS
            ? `rainbow://wc?uri=${encodeURIComponent(uri)}&connector=rainbowkit`
            : `https://rnbwapp.com/wc?uri=${encodeURIComponent(uri)}&connector=rainbowkit`,
    },
    {
        id: 'bitget',
        displayName: 'Bitget Wallet',
        rdns: ['com.bitget.web3'],
        nativeIds: {
            evm: ['bitkeep'],
            svm: ['Bitget'],
            tron: ['BitKeep'],
            bitcoin: ['bitget'],
        },
        nameAliases: ['bitkeep', 'bitget'],
        featuredRank: 4,
        iconKey: 'bitget',
        deepLink: uri => `bitkeep://wc?uri=${encodeURIComponent(uri)}`,
    },
    {
        id: 'okx',
        displayName: 'OKX Wallet',
        rdns: ['com.okex.wallet'],
        nativeIds: {
            svm: ['OKX Wallet'],
            bitcoin: ['com.okex.wallet.bitcoin'],
        },
        nameAliases: ['okx', 'okxwallet'],
        featuredRank: 5,
        deepLink: uri => `okex://main/wc?uri=${encodeURIComponent(uri)}`,
    },
    {
        id: 'walletconnect',
        displayName: 'WalletConnect',
        nativeIds: { evm: ['walletConnect'], svm: ['WalletConnect'] },
        featuredRank: 6,
        iconKey: 'walletConnect',
    },
    {
        id: 'coinbase',
        displayName: 'Coinbase Wallet',
        rdns: ['com.coinbase.wallet'],
        nativeIds: { evm: ['coinbaseWalletSDK'], svm: ['Coinbase Wallet'] },
        nameAliases: ['coinbasewalletsdk'],
        featuredRank: 7,
        iconKey: 'coinbase',
        flags: { svmTreatLoadableAsInstalled: true },
    },
    {
        id: 'phantom',
        displayName: 'Phantom',
        rdns: ['app.phantom'],
        nativeIds: { evm: ['phantom'], svm: ['Phantom'] },
        iconKey: 'phantom',
    },
    {
        id: 'trust',
        displayName: 'Trust Wallet',
        rdns: ['com.trustwallet.app'],
        nativeIds: { svm: ['Trust'], bitcoin: ['trust-bitcoin'] },
        nameAliases: ['trust'],
    },
    {
        id: 'immutable-passport',
        displayName: 'Immutable Passport',
        rdns: ['com.immutable.passport'],
        iconKey: 'imtblPassport',
    },
    {
        id: 'injected',
        nativeIds: { evm: ['injected'] },
        iconKey: 'browser',
    },
    {
        id: 'braavos',
        displayName: 'Braavos',
        nativeIds: { starknet: ['braavos'] },
        iconKey: 'braavos',
        installUrls: { chrome: 'https://chromewebstore.google.com/detail/braavos-starknet-wallet/jnlgamecbpmbajjfhmmmlhejkemejdma' },
    },
    {
        id: 'ready-x',
        displayName: 'Ready X',
        nativeIds: { starknet: ['argentX'] },
        iconKey: 'argentX',
        installUrls: { chrome: 'https://chromewebstore.google.com/detail/argent-x-starknet-wallet/dlcobpjiigpikoobohmabehhmhfoodbb' },
    },
    {
        id: 'keplr',
        displayName: 'Keplr',
        nativeIds: { starknet: ['keplr'] },
        installUrls: { chrome: 'https://chromewebstore.google.com/detail/keplr/dmkamcknogkgcdfhhbddcghachkejeap' },
    },
    {
        id: 'xverse',
        displayName: 'Xverse Wallet',
        nativeIds: { starknet: ['xverse'], bitcoin: ['XverseProviders.BitcoinProvider'] },
        nameAliases: ['xverse'],
        installUrls: { chrome: 'https://chromewebstore.google.com/detail/xverse-bitcoin-crypto-wal/idnnbdplmphpflfnlkomgpfbpcgelopg' },
    },
    {
        id: 'solflare',
        displayName: 'Solflare',
        nativeIds: { svm: ['Solflare'] },
        iconKey: 'solflare',
    },
    {
        id: 'glow',
        displayName: 'Glow',
        iconKey: 'glow',
    },
    {
        id: 'fuel-wallet',
        displayName: 'Fuel Wallet',
        nativeIds: { fuel: ['Fuel Wallet'] },
        iconKey: 'fuel',
    },
    {
        id: 'fuelet',
        displayName: 'Fuelet Wallet',
        nativeIds: { fuel: ['Fuelet Wallet'] },
        iconKey: 'fuelet',
    },
    {
        id: 'bako-safe',
        displayName: 'Bako Safe',
        nativeIds: { fuel: ['Bako Safe'] },
        iconKey: 'bakoSafe',
    },
    {
        id: 'ethereum-wallets',
        displayName: 'Ethereum Wallets',
        iconKey: 'ethereum',
    },
    {
        id: 'solana-wallets',
        displayName: 'Solana Wallets',
        iconKey: 'solana',
    },
    {
        id: 'ton',
        displayName: 'TON',
        iconKey: 'ton',
    },
    {
        id: 'tonkeeper',
        displayName: 'Tonkeeper',
        nativeIds: { ton: ['tonkeeper'] },
        iconKey: 'tonkeeper',
    },
    {
        id: 'openmask',
        displayName: 'OpenMask',
        nativeIds: { ton: ['openmask'] },
        iconKey: 'openmask',
    },
    {
        id: 'mytonwallet',
        displayName: 'MyTonWallet',
        nativeIds: { ton: ['mytonwallet'] },
        iconKey: 'mytonwallet',
    },
    {
        id: 'telegram-wallet',
        displayName: 'Wallet in Telegram',
        nativeIds: { ton: ['telegram-wallet'] },
    },
]
