packages:
  - packages/**
  - apps/bridge

catalog:
  '@wagmi/connectors': 5.7.7
  '@wagmi/core': 2.16.4
  '@types/react': 18.3.1
  axios: 1.12.2
  react: 18.3.1
  react-dom: 18.3.1
  wagmi: 2.14.11
  viem: ^2.21.16
  zustand: ^4.5.1
  "@tanstack/react-query": "^5.90.5"
  swr: "^2.2.5"