export type {
    InternalConnector,
    Wallet,
    WalletConnectionProvider,
    WalletConnectionProviderProps,
    WalletConnectionStore,
    WalletProviderStoreRegistry,
    WalletProviderDescriptor,
    MultiStepHandler,
    SelectAccountProps,
    RequestAdditionalConnectorsParams,
    RequestAdditionalConnectorsResult,
    WalletModalConnector,
    WalletWrapperProps,
    WalletInitContext,
    WalletWrapper,
    WalletProvider,
    WalletProviderModule,
    BaseWalletProviderConfig,
} from '@layerswap/wallet-core/types';
export { isWalletProviderDescriptor } from '@layerswap/wallet-core/types';
