// Generated by scripts/generate-react-shares.mjs. Do not edit.
import type { SharedLib } from '@layerswap/widget-js';

export async function loadHostReactShares(reactVersion: string, reactDOMVersion: string): Promise<Record<string, SharedLib>> {
  reactVersion = reactVersion.split('-')[0];
  reactDOMVersion = reactDOMVersion.split('-')[0];
  if (reactVersion !== reactDOMVersion || !/^(18|19)\./.test(reactVersion)) {
    throw new Error('[layerswap/widget-react] React and ReactDOM must have the same supported version (18 or 19).');
  }
  const namespaces = await Promise.all([
    import("react"),
    import("react-dom"),
    import("react-dom/client"),
    import("react-dom/server"),
    import("react/jsx-dev-runtime"),
    import("react/jsx-runtime"),
  ]);
  const modules = namespaces.map((namespace) => ('default' in namespace ? namespace.default : namespace));
  return {
    "react": { version: reactVersion, lib: () => modules[0], requiredVersion: ">=18.0.0 <20.0.0" },
    "react-dom": { version: reactDOMVersion, lib: () => modules[1], requiredVersion: ">=18.0.0 <20.0.0" },
    "react-dom/client": { version: reactDOMVersion, lib: () => modules[2], requiredVersion: ">=18.0.0 <20.0.0" },
    "react-dom/server": { version: reactDOMVersion, lib: () => modules[3], requiredVersion: ">=18.0.0 <20.0.0" },
    "react/jsx-dev-runtime": { version: reactVersion, lib: () => modules[4], requiredVersion: ">=18.0.0 <20.0.0" },
    "react/jsx-runtime": { version: reactVersion, lib: () => modules[5], requiredVersion: ">=18.0.0 <20.0.0" },
  };
}
