name: Storybook PR Preview

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

# The deploy job needs write perms; the build job stays read-only
permissions:
  contents: read
  pull-requests: write

concurrency:
  group: "pr-preview-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # IMPORTANT: check out the PR HEAD from the fork safely
      - name: Checkout PR code (from fork)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - run: yarn install --frozen-lockfile
      - run: yarn build-storybook
      - name: Upload Storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: storybook-static
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # elevate only here
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Download Storybook artifact
        uses: actions/download-artifact@v4
        with:
          name: storybook-static
          path: storybook-static

      - name: Deploy PR Preview to Pages
        id: preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: storybook-static
          umbrella-dir: pr-preview
          comment: false

      - name: Comment preview link on PR (sticky)
        if: steps.preview.outputs.deployment-action == 'deploy'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: storybook-preview
          message: |
            🚀 **Storybook preview:** ${{ steps.preview.outputs.preview-url }}

      - name: Show Preview URL
        if: always()
        run: |
          echo "Preview: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-preview/pr-${{ github.event.pull_request.number }}/" >> $GITHUB_STEP_SUMMARY
