name: Storybook PR Preview (Pages Deployments, no gh-pages)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pages: write       # needed for actions/deploy-pages
  id-token: write    # needed for actions/deploy-pages
  pull-requests: write

concurrency:
  group: "pr-preview-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build-storybook
      # upload the static Storybook as a Pages artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages (Preview)
        id: deployment
        uses: actions/deploy-pages@v4

  comment:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Comment preview link on PR (sticky)
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: storybook-preview
          message: |
            🚀 **Storybook preview:** ${{ needs.deploy.outputs.page_url || steps.deploy.outputs.page_url }}
