name: Deploy branch/commit previews

on:
  push:
    branches: ['*']  

permissions:
  contents: write

concurrency:
  group: preview-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          yarn
          yarn build-storybook
      - name: Preview Pages
        uses: rajyan/preview-pages@v1
        with:
          source-dir: storybook-static