name: Storybook PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["**"]

permissions:
  contents: read
  pages: write           # needed for deploy-pages
  id-token: write        # needed for OIDC with deploy-pages
  pull-requests: write   # for commenting

concurrency:
  group: "pr-preview-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build-storybook

      # Upload the Storybook as an artifact for Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./storybook-static

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # PR previews require this
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages (PR preview)
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true

      - name: Comment preview link on PR (sticky)
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: storybook-preview
          message: |
            🚀 **Storybook preview:** ${{ steps.deployment.outputs.page_url }}