name: Deploy Storybook (per-branch)

on:
  push:
    branches:
      - '**'           
      - '!gh-pages'    

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        run: |
          yarn install --frozen-lockfile
          yarn build-storybook -o storybook-static

      - name: Publish to gh-pages under branches/<branch>
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          publish_dir: storybook-static
          destination_dir: branches/${{ github.ref_name }}
          keep_files: true