name: Storybook – PR Preview (Pages subpath)

on:
  pull_request:
    branches: ["**"]

permissions:
  contents: write        # <-- must be write so it can push to gh-pages
  pull-requests: write   # <-- so it can comment the preview link

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: yarn build-storybook

      # Publishes to: https://<user>.github.io/<repo>/pr-preview/pr-<number>/
      - name: Deploy PR Preview to GitHub Pages
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: storybook-static
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          comment: true         