name: Dev to dev-prod && dev-stage
on: 
  push:
    branches: [dev]
permissions:
  contents: write
jobs:
  rebase-dev-prod:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge dev to dev-prod
      run: |
          git fetch --unshallow
          git checkout dev-prod
          git rebase dev
          git push

  rebase-dev-stage:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge dev to dev-stage
      run: |
          git fetch --unshallow
          git checkout dev-stage
          git rebase dev
          git push          

