name: My main workflow

on:
  push:
    branches: [main]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      # Build the application and generate source maps
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build

      # Inject and upload source maps using this action
      - name: Inject & upload source maps to PostHog
        uses: PostHog/upload-source-maps@v0.4.6
        with:
          directory: .next
          env-id: '213461'
          cli-token: 'phx_eDyryrgELEVOyzBwydBHQ4QwShawMfWSduNLKGpVsqycLYw'
