export type Commit = {
    dstAddress: string,
    dstChain: string,
    dstAsset: string,
    srcAsset: string,
    sender: string,
    srcReceiver: string,
    timelock: number,
    amount: number,
    locked: boolean,
    id: string | undefined,
    hashlock: string | undefined,
    uncommitted: boolean,
    unlocked?: boolean,
    secret: number,
    redeemed: boolean,
}